
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "> Check out current repository"
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: "> Run scripts"
        shell: bash
        run: |
          echo "Workflow step executed from > $(pwd)";
          cd "${{github.workspace}}/scripts/";
          echo "----------------------------------------";
          python "_compile.py";
